### ISSUE TITLE
failure running against WebSiteOne slack

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/project_metric_slack_trends#1]
```
TypeError: no implicit conversion of Symbol into Integer
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rasem-0.7.1/lib/rasem/svg_image.rb:426:in `[]'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/rasem-0.7.1/lib/rasem/svg_image.rb:426:in `initialize'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/bundler/gems/project_metric_slack_trends-56f1a3c99537/lib/project_metric_slack_trends.rb:40:in `new'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/bundler/gems/project_metric_slack_trends-56f1a3c99537/lib/project_metric_slack_trends.rb:40:in `image'
    from /Users/tansaku/Documents/GitHub/AgileVentures/projectscope_mvp/app/models/project.rb:29:in `block in resample_all_metrics'
    from /Users/tansaku/Documents/GitHub/AgileVentures/projectscope_mvp/app/models/project.rb:21:in `each'
    from /Users/tansaku/Documents/GitHub/AgileVentures/projectscope_mvp/app/models/project.rb:21:in `resample_all_metrics'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
    from (irb):3
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by tansaku** [comment]
so that's green locally for me, now @mtc2013 's fix is merged to master, but I still get the same error when integrated with the rails system ... hmm ...

**Comment by tansaku** [comment]
So I'm tracing the system on both the rails integrated and the standalone gem.  Here's the trace from the standalone:

``` sh
→ ber spec/project_metric_slack_trends_spec.rb:86
Run options: include {:locations=>{"./spec/project_metric_slack_trends_spec.rb"=>[86]}}

[6, 15] in /Users/tansaku/Documents/GitHub/AgileVentures/project_metric_slack_trends/lib/project_metric_slack_trends.rb
    6: 
    7:   attr_reader :raw_data
    8: 
    9:   def initialize credentials, raw_data = nil
   10:     byebug
=> 11:     @raw_data = raw_data
   12:     @channel = credentials[:channel]
   13:     @client = Slack::Web::Client.new(token: credentials[:token])
   14:   end
   15: 
(byebug) credentials
{:channel=>"websiteone", :token=>"SNIP"}
(byebug) c

[36, 45] in /Users/tansaku/Documents/GitHub/AgileVentures/project_metric_slack_trends/lib/project_metric_slack_trends.rb
   36: 
   37:     max_y = 10
   38:     min_y = 90
   39:     y_positions = calculate_positions_of_scores_on_graph(max_y,min_y)
   40:     byebug
=> 41:     unless @image
   42:       image = Rasem::SVGImage.new(120,110) do
   43:         group :class => "grid y-grid" do
   44:           line(20,0,20,90)
   45:         end
(byebug) y_positions
[NaN, 89.19567567567567, NaN]
(byebug) @image
nil
```

seems odd that two of these y_positions should be NaN at this point ... still waiting for the rails integrated version to hit the second breakpoint - slow slack queries backing this difficult to debug.  Also a little concerned that the svg gem (though it looks lovely) leads to stack traces that are not very easy to debug ...

**Comment by tansaku** [comment]
okay, the rails integrated one hit the same breakpoint, giving me similar:

```
[36, 45] in /Users/tansaku/.rvm/gems/ruby-2.3.1/bundler/gems/project_metric_slack_trends-c926910cf4d6/lib/project_metric_slack_trends.rb
   36: 
   37:     max_y = 10
   38:     min_y = 90
   39:     y_positions = calculate_positions_of_scores_on_graph(max_y,min_y)
   40:     byebug
=> 41:     unless @image
   42:       image = Rasem::SVGImage.new(120,110) do
   43:         group :class => "grid y-grid" do
   44:           line(20,0,20,90)
   45:         end
(byebug) y_positions
[NaN, 89.19567567567567, NaN]
```

and the credentials were the same ...

**Comment by tansaku** [comment]
turns out the base issue here was gem dependency on rasem
